# Use a Java base image
FROM openjdk:21

# Copy the JAR file from the local directory into the container 
COPY TicTacToeGame.jar .

# Define the command to run the application when the container starts
CMD ["java", "-jar", "TicTacToeGame.jar"]

